# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 16:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20181117_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thread',
        ),
        migrations.AddField(
            model_name='banners',
            name='thread',
            field=models.ForeignKey(default=datetime.datetime(2018, 11, 17, 16, 44, 28, 17083, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
