# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181117_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_id',
            field=models.IntegerField(),
        ),
    ]
