# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20181117_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
