# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_banners_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_booking_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('no_of_installments', models.IntegerField()),
                ('banner_installation_date', models.DateField()),
                ('banner_removal_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='banners',
            name='banner_id',
        ),
        migrations.AddField(
            model_name='entry',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Banners'),
        ),
    ]
