# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20181117_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
